spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      routes:
        - id: hello
          uri: http://www.phei.com.cn
          predicates:
            - Path=/hello/**
server:
  port: 9000
logging:
  level:
    ROOT: debug
