spring:
  application:
    name: eureka-consumer
server:
  port: 9000

eureka:
  client:
    serviceUrl:
      # eureka注册中心的地址，需要配置所有节点
      defaultZone: http://node1:8081/eureka/,http://node2:8082/eureka/,http://node3:8083/eureka/
      # 不注册到服务中心
    register-with-eureka: false