spring:
  application:
    name: eureka-service
server:
  port: 8083

eureka:
  instance:
    # 节点名称
    hostname: node3
  client:
    # 是否注册到Eureka server,默认为true
    register-with-eureka: true
    #是否从Eureka Server获取注册信息，默认为true
    fetch-registry: true
    serviceUrl:
      # 与Eureka Server交互的地址，需要显示配置集群的所有地址，多个用英文逗号隔开
      defaultZone: http://node1:8081/eureka/,http://node2:8082/eureka/
